services:
  postgres_server:
    hostname: postgres_server
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD="local123"
      - POSTGRES_DB="feature_toggle"
    ports:
      - "5433:5432"
  feature_toggle_backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:local123@postgres_server:5432/feature_toggle
    volumes:
      - ./init.sql:/app/init.sql
    depends_on:
      - postgres_server
    ports:
      - "8080:8080"
