name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        options: >
          --env POSTGRES_PASSWORD="local123"
          --env POSTGRES_DB="feature_toggle"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: local123
          POSTGRES_DB: feature_toggle

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Postgres container ID
        id: postgres_container_id
        run: echo "POSTGRES_CONTAINER_ID=$(docker ps --filter 'ancestor=postgres:latest' -q)" >> $GITHUB_ENV

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install sqlx-cli
        run: cargo install sqlx-cli --no-default-features --features postgres

      - name: Run database migrations
        working-directory: ./feature-toggle-backend
        run: sqlx migrate run --database-url postgres://postgres:local123@localhost:5432/feature_toggle

      - name: Copy SQL to the container
        run: docker cp ./init.sql ${{ env.POSTGRES_CONTAINER_ID }}:/init.sql

      - name: Execute SQL script
        run: docker exec ${{ env.POSTGRES_CONTAINER_ID }} psql -U postgres -d feature_toggle -f /init.sql

      - name: Build
        env:
          DATABASE_URL: postgres://postgres:local123@localhost:5432/feature_toggle
        run: cargo build --verbose

      # - name: Run tests
      #   env:
      #     DATABASE_URL: postgres://postgres:local123@localhost:5432/feature_toggle
      #   run: cargo test --verbose

      - name: Install llvm-tools and cargo-llvm-cov
        run: |
          rustup component add llvm-tools-preview
          cargo install cargo-llvm-cov

      - name: Run coverage
        env:
          DATABASE_URL: postgres://postgres:local123@localhost:5432/feature_toggle
        run: |
          cargo llvm-cov --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          flags: unittests
          fail_ci_if_error: true
        
